export { resetDeviceInfo } from './lib/device'
export { RxCamFactory, RxCam } from './lib/index'
export { exportFromCanvas, genCanvas, takeThumbnail } from './lib/image'
export { calcImgThumbResolution } from './lib/helper'
export * from './lib/model'
